// TRY CATCH BLOCK  
let a =7;
let b=10;
console.log("a=" ,a);
console.log("b=" ,b);
console.log("a+b=" ,a+b);

try{
    console.log("a-b=" ,a-c);// error because of which rest of the code will not be executed
}
catch(error){
    console.log("Error: ",error);
}
//  using try and catch block we can handle the error and rest of the code will be executed.


console.log("a*b=" ,a*b);

console.log("a/b=" ,a/b);
console.log("a%b=" ,a%b);
console.log("a**b=" ,a**b);
console.log("a++=" ,a++);
console.log("a--=" ,a--);
console.log("++a=" ,++a);
console.log("--a=" ,--a);
console.log("a+=b" ,a+=b);
console.log("a-=b" ,a-=b);
console.log("a*=b" ,a*=b);
console.log("a/=b" ,a/=b);
console.log("a%=b" ,a%=b);
console.log("a**=b" ,a**=b);
console.log("a==b" ,a==b);
